### ISSUE TITLE
[ BUG REPORT ] - My affinity is completely gone

### ISSUE THREAD

**Issue by BaranRadu** [Just-Natsuki-Team/NatsukiModDev#495] opened 2022-12-23 20:48 UTC
# Overview:
After the new update, my Natsuki went from LOVE to NORMAL

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment] 2022-12-23 20:49
Hi @BaranRadu,

Could you please send us your log?

**Comment by BaranRadu** [comment] 2022-12-23 20:53
==============================================================================

Fri Dec 23 22:51:54 2022
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Just Natsuki 1.0.2

[2022-12-23 22:51:54.437000] [INFO]: Current persisted version pre-mig check: 1.0.2
[2022-12-23 22:51:54.438000] [INFO]: runInitMigrations START
[2022-12-23 22:51:59.470000] [INFO]: runRuntimeMigrations START
[2022-12-23 22:51:59.470000] [INFO]: Current persisted version post-mig check: 1.0.2
[2022-12-23 22:51:59.470000] [INFO]: Daily affinity cap reached!
[2022-12-23 22:51:59.471000] [INFO]: Outfit data loaded.
[2022-12-23 22:51:59.471000] [INFO]: Outfit set.
[2022-12-23 22:51:59.471000] [INFO]: Poem data loaded.
[2022-12-23 22:51:59.471000] [INFO]: Holiday data loaded.

**Comment by Blizzardsev** [comment] 2022-12-23 20:55
Hi @BaranRadu,

Sorry - could you please upload the complete log file? I would expect a much larger log if you were at such a high affinity level.

**Comment by BaranRadu** [comment] 2022-12-23 20:56
I usually delete the game, then install it with a new update. That might explain why the log is so small

**Comment by Blizzardsev** [comment] 2022-12-23 21:03
I see. An unusual way of doing things considering you would need a fresh DDLC installation every time, but each to our own!

As for your issue, I won't beat around the bush. It looks like you've been caught by some of our new mechanics which focus on cheat prevention. As far as we are concerned, this is expected behaviour and therefore I will be closing this issue.

Thanks!

**Closed by Blizzardsev** 2022-12-23 21:03 UTC
Labels: Bug
