### ISSUE TITLE
[ BUG REPORT ] - Natsuki talks about a topic as if I already asked

### ISSUE THREAD

**Issue by disownxd** [Just-Natsuki-Team/NatsukiModDev#439] opened 2022-11-13 22:46 UTC
# Overview:
I asked her "Can you do any impressions of the other girls?", which she answered "This again?", as if I already asked before, which I didn't.

**Comment by Blizzardsev** [comment] 2022-11-13 22:51
Hi @disownxd, thanks for raising a bug report with us.

Yes, I can confirm this is indeed a bug - looks like we refer to an incorrect variable to determine if the topic has been discussed before, as we have another one with a similar name in the same context.

A fix for this would not take long, but will be part of a dedicated patch for the event other bugs become apparent as the release is still very fresh.

We'll let you know when a patch has been released. Thanks!

**Closed** 2022-12-02 21:29 UTC
Labels: Bug
