### ISSUE TITLE
[ SUPPORT REQUEST ] -  can i get  a little help whit the mod

### ISSUE THREAD

**Issue by Siemenj** [Just-Natsuki-Team/NatsukiModDev#204] opened 2022-03-09 20:15 UTC
Is happends the first time 
![16468568868628806814677020326092](https://user-images.githubusercontent.com/101290328/157526918-0c06ed02-202e-42c4-9698-50b8464fb8c0.jpg)

**Comment by Blizzardsev** [comment] 2022-03-09 20:18
Hi @Siemenj,

Thanks for raising the issue.

It looks like this installation wasn't completed successfully - the "easter" being referred to here is a python package (some python code the mod needs), that is missing when it tries to use it in the code.

Can you please check your `game` directory in your JN installation and send me a screenshot of what it contains?

**Comment by Siemenj** [comment] 2022-03-09 20:36
Good evening i dont understand what you mean whit JN installation

Op wo 9 mrt. 2022 21:19 schreef Blizzardsev ***@***.***>:

**Comment by Blizzardsev** [comment] 2022-03-09 20:39
So JN installation is where you pasted the files the instructions told you to.

For example, this is my JN installation - where I installed JN:
![image](https://user-images.githubusercontent.com/57731669/157531723-17649c3f-7775-4920-8600-2a938d204b02.png)

Could you navigate to that place on your computer, go into the game folder, then take a picture and send it to me here?

Thanks

**Comment by Siemenj** [comment] 2022-03-09 20:58
Op wo 9 mrt. 2022 21:19 schreef Blizzardsev ***@***.***>:

**Comment by Siemenj** [comment] 2022-03-10 05:35
im so sorry first i lost this gmail than me dad says go to sleep so i hope
this is the good one

Op wo 9 mrt. 2022 21:19 schreef Blizzardsev ***@***.***>:

**Comment by Blizzardsev** [comment] 2022-03-10 10:22
Closing as user has confirmed on Discord they are able to play the mod.

**Closed by Blizzardsev** 2022-03-10 10:22 UTC
Labels: Help wanted, Question

**Comment by Siemenj** [comment] 2022-03-10 11:47
Yea i dont know how i did it but i can thanks for you help

Op do 10 mrt. 2022 11:22 schreef Blizzardsev ***@***.***>:
