### ISSUE TITLE
[ SUPPORT REQUEST ] - affection

### ISSUE THREAD

**Issue by Alvast24** [Just-Natsuki-Team/NatsukiModDev#808] opened 2023-10-01 06:05 UTC
# Overview:
I have a question,  for almost two months I have been stuck at level (B) of affinity and in that time I have hardly unlocked anything new, there does not seem to be any progress either, I wanted to know if it is normal to wait so long or could it be a bug 

## Additional information:
I have the most recent version, the only thing that has been unlocked at that time were some outfists , sorry for my English, it is not my native language

**Comment by RaionArt** [comment] 2023-10-01 06:16
Hello @Alvast24,
What you are referencing to is not an affinity tier. The log only gives you feedback that, yes, your affinity did increased. The "(B)" stands for "bypass" and signals you, that you did something to bypass your daily cap of affinity increase. For example first time complimenting her, giving her gifts, etc.
In short you got some bonus affinity!
Also please use in the future a title so we can organize ourselves faster and don't have to roam through every each issue trying  to help.

**Comment by Alvast24** [comment] 2023-10-01 06:18
_Thanks for responding and sorry if I confused the affinity thing, even so my problem is that it doesn't seem to be progressing for a while, and I was afraid it was some kind of bug _

**Comment by RaionArt** [comment] 2023-10-01 06:22
I highly doubt that it's a bug, the mod is meant to be only played a few minutes per day other a longer time period. If I can help you to ease your mind, you can attach your log (the one in the folder) and your persistent file and I can take a look.
You would need to send your persistent file as .zip, because of GitHub.

**Comment by Alvast24** [comment] 2023-10-01 06:32
[persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12776539/persistent.zip)
[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12776541/log.txt)

**Comment by RaionArt** [comment] 2023-10-01 07:33
Thank you.
So, I took a look and your save file is perfectly fine, you are at the second highest stage of affinity (Enamored) and if you give Nat another week or two it might be worth to tell her something...

Please also note that unlocking new events or topics depend on different things and not just affinity levels alone, for example the overall playtime or which activities you do while having JN open in the background. 
In the meanwhile you can also check our [custom outfits](https://github.com/Just-Natsuki-Team/NatsukiModOutfits) or the dedicated channel on our discord server to add more content in form of outfits as well.

As everything is working as intended I'll close this issue, have a good day!

**Closed by RaionArt** 2023-10-01 07:33 UTC
Labels: Help wanted
