### ISSUE TITLE
[ SUPPORT REQUEST ] - messing around and time travel

### ISSUE THREAD

**Issue by Vinidy2** [Just-Natsuki-Team/NatsukiModDev#885] opened 2024-03-12 21:42 UTC
I was messing around to try everything the mod has to offer and yes, time travel events are one of those things i wanted to test. I know it does bad repercussions but i still wanted to try. Currently, when opening the game at current time, the game will glitch out playing backward music and static filling the screen meanwhile Natsuki is gone.

She never gave me a warning and i dont know if waiting on that error thing will lead to anything. What does this error thingy means? And is there a way to play the game normally in current time without restarting a new game? 

Ty :D

**Comment by Blizzardsev** [comment] 2024-03-13 01:56
Hi @Vinidy2 - for this to take place, multiple instances of time travel must have occurred - including an explicit warning from Natsuki herself. What you are describing is indeed intended behaviour as a result of your actions.

Given this warning, your explicit understanding of cheating and its consequences as well as our stance on the matter, we'll be closing this ticket - you may choose to start a new game if you so wish.

**Closed by Blizzardsev** 2024-03-13 01:56 UTC
Labels: Help wanted
